apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-k8s-hands-on
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend-k8s-hands-on:v1
        #image: nginx:alpine
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-k8s-hands-on
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # Port inside the cluster
      targetPort: 80 # Port in the container (nginx) - Si targetPort = port podemos eliminar targetPort (su default value es el mismo que el port)
