apiVersion: v1
kind: ConfigMap
metadata:
    name: vars
    labels:
        app: front
data:
    db_host: dev.host.local  # nos servirán como env vars
    db_user: dev_user
    script: |
        echo DB host es $DB_HOST y DB user es $DB_USER > /usr/share/nginx/html/test.html

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: vars
                  key: db_host
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: vars
                  key: db_user
          volumeMounts:
          - name: script-vol
            mountPath: /opt
      volumes:
        - name: script-vol
          configMap:
            name: vars
            items:
            - key: script
              path: script.sh




