apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s-hands-on
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: k8s-hands-on:v2
        imagePullPolicy: IfNotPresent  # para que intente primero con image de local en lugar de repo remoto
---
apiVersion: v1
kind: Service
metadata:
  name: backend-k8s-hands-on
  labels:
    app: backend
spec:
  # Default: ClusterIP (no accesible desde el exterior del cluster)
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80 # Port inside the cluster
      targetPort: 9090 # Port in the container
