apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"  #1 cpu entera (1000mCores)
      requests:
        cpu: "0.5" #0.5 cpu (500mCores)
    args:  #estamos solicitando más valor que el límite. K8s no reiniciará el pod al excederse el límite de cpu, tan sólo asegurará que dispone el valor máximo
    - -cpus
    - "2"
