apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "1000Gi" #Solicitamos cantidad unreachable
      limits:
        memory: "1000Gi" #Solicitamos cantidad unreachable
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250", "--vm-hang", "1"]  
