apiVersion: v1
kind: Pod
metadata:
  name: goproxy
  labels:
    app: goproxy
spec:
  containers:
  - name: goproxy
    image: registry.k8s.io/goproxy:0.1
    ports:
    - containerPort: 8080
    readinessProbe: # valida el puerto, pero él no es responsable de reiniciar el container. Desregistra los puertos del servicio si hay error, elimina la IP
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080  # cada 20 segs contra el puerto del container
      initialDelaySeconds: 15
      periodSeconds: 20
