apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: svc-clusterrole
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]  # todos los verbos: podrá ver todos los servicios del cluster y hacer cualquier cosa con estos services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-svc
subjects:
- kind: Group
  name: dev # grupo designado en CN del certificado
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: svc-clusterrole
  apiGroup: rbac.authorization.k8s.io
