---
apiVersion: v1
kind: Namespace
metadata:
    name: ci
    labels:
        name: ci
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s-hands-on
  namespace: ci
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: k8s-hands-on
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: backend-k8s-hands-on
  namespace: ci
  labels:
    app: backend
spec:
  # Default: ClusterIP (no accesible desde el exterior del cluster)
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80 # Port inside the cluster
      targetPort: 9090 # Port in the container
