---
apiVersion: v1
kind: Namespace
metadata:
    name: dev
    labels:
        name: dev
---
apiVersion: v1
kind: Namespace
metadata:
    name: prod
    labels:
        name: prod
---
apiVersion: apps/v1
kind: Deployment #visible con kubectl api-resources
metadata:
  name: deployment-dev
  namespace: dev
  labels:
    app: front
spec: #ReplicaSet
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front #debe cumplir con la label de arriba
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: apps/v1
kind: Deployment #visible con kubectl api-resources
metadata:
  name: deployment-prod
  namespace: prod
  labels:
    app: back
spec: #ReplicaSet
  replicas: 5
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: nginx
        image: nginx:alpine