apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: default
    name: sa-reader
rules:
- apiGroups: [""] # ""indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: sa-pods
    namespace: default
subjects:
- kind: ServiceAccount
  name: serviceaccounttest
  apiGroup: ""
roleRef:
    kind: Role #Role or ClusterRole
    name: sa-reader
