apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
stringData:
  username: admin
  password: t0p-Secret
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    volumeMounts:
    - name: test
      mountPath: "/opt"
      readOnly: true
  volumes:
  - name: test
    secret:
      secretName: secret1
      items:  # Si no especificamos items, se van a crear files dentro del dir (/opt) con el nombre de las llaves/valores
      - key: username
        path: user.txt  #montamos sólo el user en un file nuevo (irá en /opt)

