apiVersion: v1
kind: Secret
metadata:
  name: mysecret3
type: Opaque
stringData:
  #username: $USER  -> error: k8s tomará el valor literal del string, no fija el valor de la variable de entorno
  #password: $PASSWORD
